OPENAI_API_KEY="sk-JCguguFQg0yjwHTDNx2J90CrGku2a0iZf02HgYInRGT3BlbkFJpgN49P5MfDGiOa7pN-7h8_0A581s0VpHkap-F7BPoA"
ELEVEN_LABS_KEY= "sk_6db943dd17d2f3aa1db474cb1a6bdbe71c7290d056f3f387"
GOOGLE_MAPS_KEY="AIzaSyA4M6yxogz-1dhvvoGxLIoKjgPE92qZ4_8"